global:
  smtp_from: 'alertmanager@example.org'

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 1s
  group_interval: 1m
  repeat_interval: 3h

  receiver: default

receivers:
  - name: 'default'
    webhook_configs:
      -
        url: http://webhook:8080
